[gemini]
api_key="AIzaSyAwQOX22INQ78rtf7G3XVSGuop7QieRwjg"

[mongodb]
username="pathadem019"
password="Nino@1356"
url="mongodb+srv://pathadem019:Nino@1356@devcluster.29wvn4b.mongodb.net/?retryWrites=true&w=majority&appName=DevCluster"